apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: redis
  generation: 2
  name: redis
spec:
  dockerImageRepository: 'registry.felix.com/devops/redis'
  tags:
    - from:
        kind: DockerImage
        name: 'registry.felix.com/devops/redis:latest'
      generation: 2
      name: 'latest'